import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import PageBody from "@/components/PageBody";
import FontawesomeConfig from "./fortawesome";
import Authprovider from "@/components/Authprovider/Authprovider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontawesomeConfig />
      </head>
      <Authprovider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >        
        <PageBody>
          {children}
        </PageBody>
      </body>
      </Authprovider>
    </html>
  );
}
